main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paradox.urls')),
    
]
if settings.DEBUG:

    urlpatterns = urlpatterns+static(settings.MEDIA_URL,

    document_root=settings.MEDIA_ROOT)

paradox/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('login', views.login, name='login'),
	path('register', views.register, name='register'),
	path('home', views.home, name='home'),
	path('science', views.science, name="science"),
	path('art', views.art, name="art"),
	path('history', views.history, name="history"),
	path('technology', views.technology, name="technology"),
	path('business', views.business, name="business"),
	path('detail/<str:slug>', views.detail, name="detail"),
	path('logout', views.logout, name="logout")
]

paradox/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth import get_user_model
import uuid
from autoslug import AutoSlugField
User = get_user_model()

CATEGORIES = (
	('Science', 'Science'),
	('Art', 'Art'),
	('History', 'History'),
	('Technology', 'Technology'),
	('Business', 'Business'),

)

class Profile(models.Model):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	id_user = models.IntegerField(null=True)
	phone_number = models.IntegerField(null=True)
	how_did_you_hear_about_us = models.TextField()
	what_will_you_use_paradox_for = models.TextField()

	def __str__(self):
		return self.user.username

class FlashCard(models.Model):
	title = models.CharField(max_length=999, unique=True, null=True)
	slug = AutoSlugField(populate_from="title", unique=True, null=True)
	featured_image = models.ImageField(upload_to="files/flashcard title images", null=True, help_text="upload an image with a resolution of 375x360")
	author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	description = models.TextField(null=True)
	category = models.CharField(max_length=400, choices=CATEGORIES, null=True )
	date_created = models.DateTimeField(null=True, auto_now_add=True)


	def __str__(self):
		return self.title

class Slide(models.Model):
	title = models.CharField(max_length=300, unique=True, null=True)
	description = models.TextField(null=True)
	flashcard = models.ForeignKey(FlashCard, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return self.title

# Create your models here.

paradox/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import *
import requests
import wikipedia




"""
<_----------------------Comments in regards to debugging and maintainance of Paradox code.----------------------->
If it works don't touch it...


"""



def index(request):
	user = request.user
	if user.is_authenticated:
		return redirect('home')
	return render(request, 'index2.html')



# <==================== Auth Views Start =====================>
def login(request):
	user = request.user
	if user.is_authenticated:
		return redirect('home')
	if request.method == 'POST':
		username = request.POST['username'] #Requesting Username
		password = request.POST['password'] #Requesting Password
    
		user = auth.authenticate(username=username, password=password)

		if user is not None: #Cheking If User Exists in the database
			auth.login(request, user) # Logs in User
			return redirect('home') # REdirects to home view
		else:
			messages.info(request, 'Invalid Username or Password') #Conditional Checkign if credentials are correct
			return redirect('login')#Redirects to login if invalid
	else:
		return render(request, 'login.html', {'title' : 'Login'})


def register(request):
	user = request.user
	if user.is_authenticated:
		return redirect('home')
		
	if request.method == "POST":
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']
		username = request.POST['username']
		email = request.POST['email']
		password = request.POST['password']
		password2 = request.POST['password2']

		if password == password2:
			if User.objects.filter(email=email).exists():
				messages.info(request, "This email is already in use")
				return redirect("register")
			elif User.objects.filter(username=username).exists():
				messages.info(request, "This username is alrready in use")
				return redirect("register")

			else:
				user = User.objects.create_user(username=username, password=password, first_name=first_name, last_name=last_name)
				user.save()
				user_login = auth.authenticate(username=username, password=password)
				auth.login(request, user_login)

			user_model = User.objects.get(username=username)
			new_profile = Profile.objects.create(user=user_model, id_user=user_model.id)
			new_profile.save()
			return redirect("home")

		else:
			messages.info(request, "Passwords do not match")
			return redirect("register")
	else:
		return render(request, 'register.html', {'title' : 'Register'})
	

@login_required
def home(request):
	flashcard = FlashCard.objects.all().order_by('date_created')[:8]
	context = {
		'flashcard' : flashcard,
		'title' : 'Home'
	}
	return render(request, 'home.html', context)

@login_required
def science(request):
	flashcard = FlashCard.objects.filter(category="Science")
	context = {
		'flashcard' : flashcard,
		'title' : 'Science'
	}
	return render(request, 'category.html', context, {'title' : 'Flashcards on Science'})

@login_required
def art(request):
	flashcard = FlashCard.objects.filter(category="Art")
	context = {
		'flashcard' : flashcard,
		'title' : 'Art'
	}
	return render(request, 'category.html', context, {'title' : 'Flashcards on Art'})

@login_required
def history(request):
	flashcard = FlashCard.objects.filter(category="History")
	context = {
		'flashcard' : flashcard,
		'title' : 'History'
	}
	return render(request, 'category.html', context, {'title' : 'Flashcards on History'})

@login_required
def technology(request):
	flashcard = FlashCard.objects.filter(category="Technology")
	context = {
		'flashcard' : flashcard,
		'title' : 'Technology'
	}
	return render(request, 'category.html', context, {'title' : 'Technology'})

@login_required
def business(request):
	flashcard = FlashCard.objects.filter(category="Business")
	context = {
		'flashcard' : flashcard,
		'title' : 'Business'
	}
	return render(request, 'category.html', context, {'title' : 'Business'})

@login_required
def detail(request, slug):
	flashcard = FlashCard.objects.get(slug=slug)

	context = {
		'flashcard' : flashcard,
		'title' : flashcard
	}

	return render(request, 'detail.html', context)

@login_required
def logout(request):
    auth.logout(request)
    return redirect('login')
# <=================== Auth Views End ========================>




# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="{% static 'assets/package/swiper.min.css' %}"/>
    <title>Paradox | {{title}}</title>
    <style>
        section{
            padding: 60px 0;
        }
        .swiper {
            width: 600px;
            height: 300px;
        }
    </style>
</head>
<body>
    <!--Nav Bar Start-->
    <nav class="navbar navbar-expand-md navbar-dark gedo animate__animated animate__backInLeft">
        <div class="container-lg">
            <a href="#" class="navbar-brand">
                <i class="bi bi-book-half"></i>
                Paradox
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end align-center" id="main-nav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="#" class="nav-link">Support Me</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a href="#sidebar" class="nav-link" data-bs-toggle="offcanvas" role="button" aria-controls="sidebar">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">Become an admin</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">Log Out</a>
                    </li>
                    <li class="nav-item gedo">
                        <div class="nav-link">
                            <div class="input-group input-group-sm flex-nowrap">
                                <span class="input-group-text">
                                    <i class="bi bi-search haha"></i>
                                </span>
                                <form method="GET">
                                    <input type="search" class="form-control no-wrap" placeholder="Search for a topic">
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!--Nav End-->


    {% block content %}

    {% endblock %}

    <!--Offcanvas Start--> 
    <div class="offcanvas offcanvas-start gedo" tabindex="-1" id="sidebar" aria-labelledby="sidebar-label">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title header-color fw-bold" id="sidebar-label">Categories</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-body">
            <a href="{% url 'science' %}" style="color: whitesmoke; text-decoration: none;"><p class="lead ms-3"><i class="bi bi-flask me-2"></i>Science</p></a>
            <a href="{% url 'art' %}" style="color: whitesmoke; text-decoration: none;"><p class="lead ms-3"><i class="bi bi-briefcase me-2"></i>Art</p></a>
            <a href="{% url 'history' %}" style="color: whitesmoke; text-decoration: none;"><p class="lead ms-3"><i class="bi bi-book me-2"></i>History</p></a>
            <a href="{% url 'business' %}" style="color: whitesmoke; text-decoration: none;"><p class="lead ms-3"><i class="bi bi-check-all me-2"></i>Business</p></a>
            <a href="{% url 'technology' %}" style="color: whitesmoke; text-decoration: none;"><p class="lead ms-3"><i class="bi bi-award me-2"></i>Technology</p></a>
            <a href="#" style="color: whitesmoke; text-decoration: none;"><p class="lead ms-3"><i class="bi bi-briefcase-fill me-2"></i>History</p></a>
        </div>
        
        <div class="offcanvas-footer">
            <a href="{% url 'logout' %}" style="text-decoration: none; color: black;"><p class="lead ms-3"><i class="bi bi-box-arrow-left me-2"></i><span style="color: red;">Logout</span></p></a>
        </div>

    </div>
    <!--Offcanvas End-->

    <script src="{% static 'assets/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'assets/package/swiper-bundle.js' %}"></script>
    <script type="text/javascript">
        const swiper = new Swiper('.swiper', {
          // Optional parameters
          direction: 'vertical',
          loop: true,

          // If we need pagination
          pagination: {
            el: '.swiper-pagination',
          },

          // Navigation arrows
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
          },

          // And if we need scrollbar
          scrollbar: {
            el: '.swiper-scrollbar',
          },
        });
    </script>
</body>
</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    {% block css %}
    {% endblock css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <title>Home | {{title}}</title>
    <style>
        section{
            padding: 60px 0;
        }
    </style>
</head>
<body>
    <!--Nav Bar Start-->
    <nav class="navbar navbar-expand-md navbar-dark gedo animate__animated animate__flipInY" data-aos="fade-up">
        <div class="container-lg">
            <a href="#" class="navbar-brand spaced">
                <i class="bi bi-book-half"></i>
                <span class="fw-bold">PARADOX</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end align-center" id="main-nav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'register' %}" class="nav-link">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link">Log in</a>
                    </li>
                    <li class="nav-item">
                        <a href="#about" class="nav-link">About</a>
                    </li>
                    <li class="nav-item">
                        <a href="mailto:tobiekundayo07@gmail.com" class="nav-link">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!--Nav End-->

    {% block content %}

    {% endblock %}

    <!---->
    <!-- FOOTER -->
    <footer class="container">
        <p class="normal-text">&copy; 2023 Tobi TheRevolutionary</p>
      </footer>

    <script src="{% static 'assets/js/bootstrap.bundle.js' %}"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>
</html>

templates/category.html
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <!--Latest Flaschcards Section Start-->
    <section id="mainfeed" class="text-center">
        <div class="container-xl">
            <div class="fw-bold">
                <h2 class="fw-bold header-color">Flashcards on {{title}}</h2>
            </div>
            <div class="row justify-content-center">
                {% for a in flashcard %}
                <div class="col-lg-3 col-md-5 gedo2 mb-4 me-2 ms-2">
                    <img src="{{a.featured_image.url}}" alt="" class="img-fluid mb-3 mt-2">
                    <h3 class="header-color fw-bold text-start">{{a.title}}</h3>
                    <p class="text-muted justice">{{a.description}}</p>
                    <div class="zedda text-start">
                        <a href="/detail/{{a.slug}}" class="btn btn-secondary">Read More</a>
                        <p class="normal-text text-start mt-3"><i class="bi bi-person"></i> {{a.author}}</p>
                    </div>
                    <hr>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!--Latest Flaschcards Section End-->
    {% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<section id="detail">
		<div class="container-lg">
			<div class="row justify-content-center align-items-center">
				<div class="text-center">
					<h3 class="header-color">{{title}}</h3>
				</div>
				<div class="col-lg-6 col-md-5 mx-3 my-5 kurama p-4">
				<!-- Slider main container -->
					<div class="swiper">
					  <!-- Additional required wrapper -->
					  <div class="swiper-wrapper">
					    <!-- Start of Slides -->
					    {% for w in flashcard.slide_set.all %}
					    <div class="swiper-slide">
					    	<h4 class="header-color">{{w.title}}</h4>
					    	<p class="normal-text">{{w.description}}</p>
					    </div>
					    {% endfor %}
					    <!-- End of Slides -->
					  </div>
					  <!-- If we need navigation buttons -->
					  <div class="swiper-button-prev"></div>
					  <div class="swiper-button-next"></div>
					  <!-- end -->
					</div>
				</div>
	        </div>
		</div>
	</section>
{% endblock %}

templates/home.html
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <!--Header 3 Column Layout Start-->
    <section id="main">
        <div class="container-xxl">
            <div class="row justify-content-center align-items-center g-2">
                <div class="col-lg-2 col-md-2 gedo me-2 p-3 d-none d-lg-block">
                    <div class="header-color">
                        <h4>Profile Info</h4>
                    </div>
                    <div class="col-4">
                        <img src="assets/img/covid.png" alt="fjhc" class="img-fluid rounded">
                    </div>
                    <div class="col">
                        <p class="normal-text text-muted"><i class="bi bi-person"></i> Agba Koda</p>
                    </div>
                    <div class="col">
                        <p class="normal-text text-muted"><i class="bi bi-phone"></i> +2349159372550</p>
                    </div>
                    <div class="col">
                        <p class="normal-text text-muted"><i class="bi bi-flag"></i> Korean</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5 gedo me-2">
                    <div id="carouselExampleCaptions" class="carousel slide">
                        <div class="carousel-indicators">
                          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                        </div>
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img src="http://via.placeholder.com/640x360" class="d-block w-100" alt="...">
                            <div class="carousel-caption">
                              <h5>First slide label</h5>
                              <p>Some representative placeholder content for the first slide.</p>
                            </div>
                          </div>
                          <div class="carousel-item">
                            <img src="http://via.placeholder.com/640x360" class="d-block w-100" alt="...">
                            <div class="carousel-caption">
                              <h5>Second slide label</h5>
                              <p>Some representative placeholder content for the second slide.</p>
                            </div>
                          </div>
                          <div class="carousel-item">
                            <img src="http://via.placeholder.com/640x360" class="d-block w-100" alt="...">
                            <div class="carousel-caption">
                              <h5>Third slide label</h5>
                              <p>Some representative placeholder content for the third slide.</p>
                            </div>
                          </div>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 gedo me-2 p-2 d-none d-md-block">
                    <div class="header-color">
                        <h4>Latest Posts</h4>
                    </div>
                    <div class="col-4">
                        <img src="assets/img/covid.png" alt="fjhc" class="img-fluid rounded">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--Header 3 Column Layout Start-->

    <!--Latest Flaschcards Section Start-->
    <section id="mainfeed" class="text-center">
        <div class="container-xl">
            <div class="fw-bold">
                <h2 class="fw-bold header-color">Latest Flashcards</h2>
            </div>
            <div class="row justify-content-center">
                {% for a in flashcard %}
                <div class="col-lg-3 col-md-5 gedo2 mb-4 me-2 ms-2">
                    <img src="{{a.featured_image.url}}" alt="" class="img-fluid mb-3 mt-2">
                    <h3 class="header-color fw-bold text-start">{{a.title}}</h3>
                    <p class="text-muted justice">{{a.description}}</p>
                    <div class="zedda text-start">
                        <a href="/detail/{{a.slug}}" class="btn btn-secondary">Read More</a>
                        <p class="normal-text text-start mt-3"><i class="bi bi-person"></i> {{a.author}}</p>
                    </div>
                    <hr>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!--Latest Flaschcards Section End-->
    {% endblock %}

templates/index2.html
    {% extends 'base2.html' %}
    {% load static %}
    {% block content %}
    <!--Hero Section Start-->
    <section id="hero">
        <div class="container-lg  animate__animated animate__backInLeft" data-aos="fade-down">
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-6 col-md-4">
                    <h3 class="header-color">Learning Made Easy</h3>
                    <p class="lead normal-text justice">Paradox is a tool that let's you learn just about anything with the help of well detailed flashcards that span across a wide range of different topics.</p>
                    <a href="#" class="btn btn-secondary btn-custom">Get Started</a>
                </div>
                <div class="col-lg-6 col-md-4 d-none d-md-block">
                    <img src="{% static 'assets/img/covid.png' %}" alt="Hero Image" class="img-fluid">
                </div>
            </div>
        </div>
    </section>
    <!--Hero Section End-->

    <!--Features Start-->
    <section id="marketing" class="gedo" data-aos="fade-down">
        <div class="container marketing">
            <div class="text-center">
                <h2 class="header-color">Features</h2>
                <p class="text-muted">What Makes Paradox Unique?</p>
            </div>
    
        <!-- Three columns of text below the carousel -->
        <div class="row justify-content-center mb-2">

            <div class="col-lg-3 gedo2 me-3 mb-2 p-4 shadow rounded-pill animate__animated animate__backInRight">
                <i class="bi bi-speedometer custom"></i>
                <h2 class="normal-text">Fast and Efficient</h2>
                <p class="normal-text">Our Flashcards are designed to help you learn and memorize anything on any topic in the fastest and most efficient ways possible</p>
                <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->

            <div class="col-lg-3 gedo2 me-3 mb-2 p-4 shadow rounded-pill animate__animated animate__backInRight">
                <i class="bi bi-folder custom"></i>
                <h2 class="normal-text">Organized</h2>
                <p class="normal-text">Flashcards on Paradox are well organized making it easy to navigate through them</p>
                <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->

            

            <div class="col-lg-3 gedo2 me-3 mb-2 p-4 shadow rounded-pill animate__animated animate__backInRight">
                <i class="bi bi-info-circle custom"></i>        
                <h2 class="normal-text">Detailed</h2>
                <p class="normal-text">Flashcards on Paradox are well detailed so as to give you a broad overview on any topic you wish to learn</p>
                <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->

        </div><!-- /.row -->
    </section>
    <!--Features End-->

    <!--Marketing Start-->
    <section id="about">
        <div class="container">
            <!--Marketing Item Start-->
            <div class="row featurette mb-4 justify-content-center align-items-center mt-3" data-aos="fade-down" data-aos-delay="300" data-aos-offset="0">
                <div class="col-md-7 order-md-2 mt-5">
                    <h2 class="featurette-heading header-color">What's Paradox? <span class="text-muted">What do I use it for?</span></h2>
                    <p class="lead normal-text">Paardox is a simple web application that uses flashcards to provide an overview on any topic that you might be interested in learning about.</p>
                </div>
                <div class="col-md-5 order-md-1">
                    <img src="{% static 'assets/img/gumball.png' %}" alt="image" class="img-fluid" width="500" height="500">
                </div>
            </div>
            <!--Marketing Item End-->

            <!--Marketing Item Start-->
            <div class="row featurette mb-4 justify-content-center align-items-center mt-3" data-aos="fade-down" data-aos-delay="300" data-aos-offset="0">
                <div class="col-md-7 mt-5">
                    <h2 class="featurette-heading header-color">Why did you make Paradox? <span class="text-muted">And no, I'm not about to drop motivational text</span></h2>
                    <p class="lead normal-text">Other than the obvious reason about me being Chad and Peak, I made Paradox to help students study better and faster with the help of well detailed flashcards that have extra resources attached to them for further learning.</p>
                </div>
                <div class="col-md-5">
                    <img src="{% static 'assets/img/R.png' %}" alt="image" width="500" height="500" class="img-fluid">
                </div>
            </div>
            <!--Marketing Item End-->

            <!--Marketing Item Start-->
            <div class="row featurette mb-4 justify-content-center align-items-center mt-3" data-aos="fade-down" data-aos-delay="300" data-aos-offset="0">
                <div class="col-md-7 order-md-2 mt-5">
                    <h2 class="featurette-heading header-color">What's the purpose of Paradox? <span class="text-muted">It's quite simple</span></h2>
                    <p class="lead normal-text">What is the purpose of anything? Well, for Paradox, it's purpose is to help people study better and wayyyyyyy more efficiently.</p>
                </div>
                <div class="col-md-5 order-md-1">
                    <img src="{% static 'assets/img/okay.jpg' %}" alt="hdfhjdf" class="img-fluid">
                </div>
            </div>
            <!--Marketing Item End-->
        </div>
    </section>
    <!--Marketing End-->
    {% endblock %}

templates/login.html
    {% extends 'base2.html' %}
    {% load static %}
    {% block css %}
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    {% endblock css %}
    {% block content %}
    <section id="login" class="">
        <div class="container-fluid vh-75" style="margin-top:70px">
            <div class="" style="margin-top:50px">
                <div class="rounded d-flex justify-content-center">
                    <div class="col-md-4 col-sm-12 shadow-lg p-5">
                        <div class="text-center">
                            <h3 class="header-color">Login</h3>
                            <p class="normal-text">Hey there, Paradox was not the same without you. Login to continue</p>
                            {% if messages %}
                            {% for message in messages %}
                            <p class="header-color">{{message}}</p>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="p-4">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder="Username" name="username">
                                </div>
                                <div class="input-group mb-3">
                                    <input type="password" class="form-control" placeholder="Password" name="password">
                                </div>
                                <button class="btn btn-secondary text-center mt-2 btn-custom" type="submit">
                                    Login
                                </button>
                                <p class="text-center mt-5 normal-text">Don't have an account?
                                    <a href="register.html" style="text-decoration: none;"><span class="text-primary">Sign Up</span></a>
                                </p>
                                <a href="#"  style="text-decoration: none;"><p class="text-center text-primary">Forgot your password?</p></a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}